# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: appointment_system
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          -- health-cmd pg_isready
          -- health-interval 10s
          -- health-timeout 5s
          -- health-retries 5

    steps:

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.2'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Run Migrations
        run: make migrateup

      - name: Test
        run: make test